# run the test suites inside the docker container on Travis CI systems
sudo: required
services:
  - docker

before_install:
  - docker build -t fayosaadi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run fayosaadi/react-test yarn test:ci

#after_success:
#  - docker build -t fayosaadi/mutli-client -f ./client
#  - docker build -t fayosaadi/mutli-nginx -f ./nginx
#  - docker build -t fayosaadi/mutli-server -f ./server
#  - docker build -t fayosaadi/mutli-worker -f ./worker
#
## Log in to docker CLI
#- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#
## Push images to docker hub
#- docker push fayosaadi/mutli-client
#- docker push fayosaadi/mutli-nginx
#- docker push fayosaadi/mutli-server
#- docker push fayosaadi/mutli-worker


