# run the test suites inside the docker container on Travis CI systems
sudo: required
services:
  - docker

before_install:
  - docker build -t fayosaadi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run fayosaadi/react-test yarn test:ci

after_success:
  - docker build -t fayosaadi/multi-client -f ./client  ./client
  - docker build -t fayosaadi/multi-nginx -f ./nginx  ./nginx
  - docker build -t fayosaadi/multi-server -f ./server  ./server
  - docker build -t fayosaadi/multi-worker -f ./worker  ./worker
#
## Log in to docker CLI
#- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#
## Push images to docker hub
#- docker push fayosaadi/multi-client
#- docker push fayosaadi/multi-nginx
#- docker push fayosaadi/multi-server
#- docker push fayosaadi/multi-worker


