version: '3'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
  redis:
    image: 'redis:latest'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PG_HOST: postgres
      PG_USER: postgres
      PG_DATABASE: postgres
      PG_PASSWORD: 1234
      PG_PORT: 5432
    depends_on:
      - postgres
  client:
    build:
      dockerfile: Dockerfile.dev
      context: client
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: nginx
    ports:
      - '8080:80'
    depends_on:
      - api
      - client
